# Generated by Django 2.2.12 on 2022-02-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20220223_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='书名'),
        ),
    ]
